name: 🚀 Deploy Version

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  cortex-m4f:
    uses: libhal/ci/.github/workflows/deploy.yml@5.x.y
    with:
      arch: cortex-m4f
      version: ${{ inputs.version }}
      os: baremetal
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
    secrets: inherit
